---
linters:
  enable:
  - revive
  - gocyclo
  - misspell

linters-settings:
  gocyclo:
    min-complexity: 15

  misspell:
    locale: US

  revive:
    rules:
    - name: unexported-return
      disabled: true
    - name: unused-parameter

  staticcheck:
    checks:
    - all
    - '-SA1019' # temporarily disable the "is deprecated" rule

issues:
  exclude-use-default: false
  exclude-case-sensitive: false
